// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CliniciansControllerCreateData, CliniciansControllerCreateErrors, CliniciansControllerCreateResponses, CliniciansControllerFindAllData, CliniciansControllerFindAllResponses, CliniciansControllerFindOneData, CliniciansControllerFindOneErrors, CliniciansControllerFindOneResponses, CliniciansControllerRemoveData, CliniciansControllerRemoveErrors, CliniciansControllerRemoveResponses, CliniciansControllerUpdateData, CliniciansControllerUpdateErrors, CliniciansControllerUpdateResponses, PatientsControllerCreateData, PatientsControllerCreateErrors, PatientsControllerCreateResponses, PatientsControllerFindAllData, PatientsControllerFindAllErrors, PatientsControllerFindAllResponses, PatientsControllerFindOneData, PatientsControllerFindOneErrors, PatientsControllerFindOneResponses, PatientsControllerRemoveData, PatientsControllerRemoveErrors, PatientsControllerRemoveResponses, PatientsControllerUpdateData, PatientsControllerUpdateErrors, PatientsControllerUpdateResponses, VisitsControllerCreateData, VisitsControllerCreateErrors, VisitsControllerCreateResponses, VisitsControllerFindAllData, VisitsControllerFindAllErrors, VisitsControllerFindAllResponses, VisitsControllerFindOneData, VisitsControllerFindOneErrors, VisitsControllerFindOneResponses, VisitsControllerRemoveData, VisitsControllerRemoveErrors, VisitsControllerRemoveResponses, VisitsControllerUpdateData, VisitsControllerUpdateErrors, VisitsControllerUpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get paginated patients list
 */
export const patientsControllerFindAll = <ThrowOnError extends boolean = false>(options?: Options<PatientsControllerFindAllData, ThrowOnError>): RequestResult<PatientsControllerFindAllResponses, PatientsControllerFindAllErrors, ThrowOnError> => (options?.client ?? client).get<PatientsControllerFindAllResponses, PatientsControllerFindAllErrors, ThrowOnError>({ url: '/patients', ...options });

/**
 * Create a patient
 */
export const patientsControllerCreate = <ThrowOnError extends boolean = false>(options: Options<PatientsControllerCreateData, ThrowOnError>): RequestResult<PatientsControllerCreateResponses, PatientsControllerCreateErrors, ThrowOnError> => (options.client ?? client).post<PatientsControllerCreateResponses, PatientsControllerCreateErrors, ThrowOnError>({
    url: '/patients',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete patient by id
 */
export const patientsControllerRemove = <ThrowOnError extends boolean = false>(options: Options<PatientsControllerRemoveData, ThrowOnError>): RequestResult<PatientsControllerRemoveResponses, PatientsControllerRemoveErrors, ThrowOnError> => (options.client ?? client).delete<PatientsControllerRemoveResponses, PatientsControllerRemoveErrors, ThrowOnError>({ url: '/patients/{id}', ...options });

/**
 * Get patient by id
 */
export const patientsControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<PatientsControllerFindOneData, ThrowOnError>): RequestResult<PatientsControllerFindOneResponses, PatientsControllerFindOneErrors, ThrowOnError> => (options.client ?? client).get<PatientsControllerFindOneResponses, PatientsControllerFindOneErrors, ThrowOnError>({ url: '/patients/{id}', ...options });

/**
 * Update patient by id
 */
export const patientsControllerUpdate = <ThrowOnError extends boolean = false>(options: Options<PatientsControllerUpdateData, ThrowOnError>): RequestResult<PatientsControllerUpdateResponses, PatientsControllerUpdateErrors, ThrowOnError> => (options.client ?? client).patch<PatientsControllerUpdateResponses, PatientsControllerUpdateErrors, ThrowOnError>({
    url: '/patients/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get paginated clinicians list
 */
export const cliniciansControllerFindAll = <ThrowOnError extends boolean = false>(options?: Options<CliniciansControllerFindAllData, ThrowOnError>): RequestResult<CliniciansControllerFindAllResponses, unknown, ThrowOnError> => (options?.client ?? client).get<CliniciansControllerFindAllResponses, unknown, ThrowOnError>({ url: '/clinicians', ...options });

/**
 * Create a clinician
 */
export const cliniciansControllerCreate = <ThrowOnError extends boolean = false>(options: Options<CliniciansControllerCreateData, ThrowOnError>): RequestResult<CliniciansControllerCreateResponses, CliniciansControllerCreateErrors, ThrowOnError> => (options.client ?? client).post<CliniciansControllerCreateResponses, CliniciansControllerCreateErrors, ThrowOnError>({
    url: '/clinicians',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete clinician by id
 */
export const cliniciansControllerRemove = <ThrowOnError extends boolean = false>(options: Options<CliniciansControllerRemoveData, ThrowOnError>): RequestResult<CliniciansControllerRemoveResponses, CliniciansControllerRemoveErrors, ThrowOnError> => (options.client ?? client).delete<CliniciansControllerRemoveResponses, CliniciansControllerRemoveErrors, ThrowOnError>({ url: '/clinicians/{id}', ...options });

/**
 * Get clinician by id
 */
export const cliniciansControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<CliniciansControllerFindOneData, ThrowOnError>): RequestResult<CliniciansControllerFindOneResponses, CliniciansControllerFindOneErrors, ThrowOnError> => (options.client ?? client).get<CliniciansControllerFindOneResponses, CliniciansControllerFindOneErrors, ThrowOnError>({ url: '/clinicians/{id}', ...options });

/**
 * Update clinician by id
 */
export const cliniciansControllerUpdate = <ThrowOnError extends boolean = false>(options: Options<CliniciansControllerUpdateData, ThrowOnError>): RequestResult<CliniciansControllerUpdateResponses, CliniciansControllerUpdateErrors, ThrowOnError> => (options.client ?? client).patch<CliniciansControllerUpdateResponses, CliniciansControllerUpdateErrors, ThrowOnError>({
    url: '/clinicians/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get paginated visits list
 */
export const visitsControllerFindAll = <ThrowOnError extends boolean = false>(options?: Options<VisitsControllerFindAllData, ThrowOnError>): RequestResult<VisitsControllerFindAllResponses, VisitsControllerFindAllErrors, ThrowOnError> => (options?.client ?? client).get<VisitsControllerFindAllResponses, VisitsControllerFindAllErrors, ThrowOnError>({ url: '/visits', ...options });

/**
 * Create a visit
 */
export const visitsControllerCreate = <ThrowOnError extends boolean = false>(options: Options<VisitsControllerCreateData, ThrowOnError>): RequestResult<VisitsControllerCreateResponses, VisitsControllerCreateErrors, ThrowOnError> => (options.client ?? client).post<VisitsControllerCreateResponses, VisitsControllerCreateErrors, ThrowOnError>({
    url: '/visits',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete visit by id
 */
export const visitsControllerRemove = <ThrowOnError extends boolean = false>(options: Options<VisitsControllerRemoveData, ThrowOnError>): RequestResult<VisitsControllerRemoveResponses, VisitsControllerRemoveErrors, ThrowOnError> => (options.client ?? client).delete<VisitsControllerRemoveResponses, VisitsControllerRemoveErrors, ThrowOnError>({ url: '/visits/{id}', ...options });

/**
 * Get visit by id
 */
export const visitsControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<VisitsControllerFindOneData, ThrowOnError>): RequestResult<VisitsControllerFindOneResponses, VisitsControllerFindOneErrors, ThrowOnError> => (options.client ?? client).get<VisitsControllerFindOneResponses, VisitsControllerFindOneErrors, ThrowOnError>({ url: '/visits/{id}', ...options });

/**
 * Update visit by id
 */
export const visitsControllerUpdate = <ThrowOnError extends boolean = false>(options: Options<VisitsControllerUpdateData, ThrowOnError>): RequestResult<VisitsControllerUpdateResponses, VisitsControllerUpdateErrors, ThrowOnError> => (options.client ?? client).patch<VisitsControllerUpdateResponses, VisitsControllerUpdateErrors, ThrowOnError>({
    url: '/visits/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
