// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type CreatePatientRequestDto = {
    givenName: string;
    familyName: string;
    dateOfBirth: string;
    gender: 'male' | 'female' | 'other' | 'unknown';
};

export type PatientInfoDto = {
    id: string;
    givenName: string;
    familyName: string;
    dateOfBirth: string;
    gender: 'male' | 'female' | 'other' | 'unknown';
    createdAt: string;
    updatedAt: string;
};

export type PaginatedPatientsInfoDto = {
    /**
     * Total number of matching records
     */
    total: number;
    /**
     * Current page number
     */
    page: number;
    /**
     * Number of items per page
     */
    limit: number;
    data: Array<PatientInfoDto>;
};

export type UpdatePatientDto = {
    givenName?: string;
    familyName?: string;
    dateOfBirth?: string;
    gender?: 'male' | 'female' | 'other' | 'unknown';
};

export type DeleteResultDto = {
    id: string;
    deleted: boolean;
};

export type CreateClinicianRequestDto = {
    givenName: string;
    familyName: string;
    dateOfBirth: string;
    gender: 'male' | 'female' | 'other' | 'unknown';
};

export type ClinicianInfoDto = {
    id: string;
    givenName: string;
    familyName: string;
    dateOfBirth: string;
    gender: 'male' | 'female' | 'other' | 'unknown';
    createdAt: string;
    updatedAt: string;
};

export type PaginatedCliniciansInfoDto = {
    /**
     * Total number of matching records
     */
    total: number;
    /**
     * Current page number
     */
    page: number;
    /**
     * Number of items per page
     */
    limit: number;
    data: Array<ClinicianInfoDto>;
};

export type UpdateClinicianDto = {
    givenName?: string;
    familyName?: string;
    dateOfBirth?: string;
    gender?: 'male' | 'female' | 'other' | 'unknown';
};

export type CreateVisitRequestDto = {
    patientId: string;
    clinicianId: string;
    visitedAt: string;
    notes?: string;
};

export type VisitInfoDto = {
    id: string;
    patient: PatientInfoDto;
    clinician: ClinicianInfoDto;
    visitedAt: string;
    notes?: string;
};

export type PaginatedVisitInfoDto = {
    /**
     * Total number of matching records
     */
    total: number;
    /**
     * Current page number
     */
    page: number;
    /**
     * Number of items per page
     */
    limit: number;
    data: Array<VisitInfoDto>;
};

export type UpdateVisitDto = {
    patientId?: string;
    clinicianId?: string;
    visitedAt?: string;
    notes?: string;
};

export type PatientsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (1-based)
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * Search term
         */
        search?: string;
        /**
         * Sort direction
         */
        sortBy?: 'ASC' | 'DESC';
        /**
         * Field to sort by
         */
        orderBy?: 'givenName' | 'familyName' | 'dateOfBirth' | 'createdAt';
    };
    url: '/patients';
};

export type PatientsControllerFindAllErrors = {
    /**
     * Invalid query parameters
     */
    400: unknown;
};

export type PatientsControllerFindAllResponses = {
    200: PaginatedPatientsInfoDto;
};

export type PatientsControllerFindAllResponse = PatientsControllerFindAllResponses[keyof PatientsControllerFindAllResponses];

export type PatientsControllerCreateData = {
    body: CreatePatientRequestDto;
    path?: never;
    query?: never;
    url: '/patients';
};

export type PatientsControllerCreateErrors = {
    /**
     * Invalid request
     */
    400: unknown;
};

export type PatientsControllerCreateResponses = {
    201: PatientInfoDto;
};

export type PatientsControllerCreateResponse = PatientsControllerCreateResponses[keyof PatientsControllerCreateResponses];

export type PatientsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/patients/{id}';
};

export type PatientsControllerRemoveErrors = {
    /**
     * Invalid UUID
     */
    400: unknown;
    /**
     * Patient not found
     */
    404: unknown;
};

export type PatientsControllerRemoveResponses = {
    200: DeleteResultDto;
};

export type PatientsControllerRemoveResponse = PatientsControllerRemoveResponses[keyof PatientsControllerRemoveResponses];

export type PatientsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/patients/{id}';
};

export type PatientsControllerFindOneErrors = {
    /**
     * Invalid UUID
     */
    400: unknown;
    /**
     * Patient not found
     */
    404: unknown;
};

export type PatientsControllerFindOneResponses = {
    200: PatientInfoDto;
};

export type PatientsControllerFindOneResponse = PatientsControllerFindOneResponses[keyof PatientsControllerFindOneResponses];

export type PatientsControllerUpdateData = {
    body: UpdatePatientDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/patients/{id}';
};

export type PatientsControllerUpdateErrors = {
    /**
     * Invalid request or UUID
     */
    400: unknown;
    /**
     * Patient not found
     */
    404: unknown;
};

export type PatientsControllerUpdateResponses = {
    200: PatientInfoDto;
};

export type PatientsControllerUpdateResponse = PatientsControllerUpdateResponses[keyof PatientsControllerUpdateResponses];

export type CliniciansControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (1-based)
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * Search term
         */
        search?: string;
        /**
         * Sort direction
         */
        sortBy?: 'ASC' | 'DESC';
        /**
         * Field to sort by
         */
        orderBy?: 'givenName' | 'familyName' | 'dateOfBirth' | 'createdAt';
    };
    url: '/clinicians';
};

export type CliniciansControllerFindAllResponses = {
    200: PaginatedCliniciansInfoDto;
};

export type CliniciansControllerFindAllResponse = CliniciansControllerFindAllResponses[keyof CliniciansControllerFindAllResponses];

export type CliniciansControllerCreateData = {
    body: CreateClinicianRequestDto;
    path?: never;
    query?: never;
    url: '/clinicians';
};

export type CliniciansControllerCreateErrors = {
    /**
     * Invalid request
     */
    400: unknown;
};

export type CliniciansControllerCreateResponses = {
    201: ClinicianInfoDto;
};

export type CliniciansControllerCreateResponse = CliniciansControllerCreateResponses[keyof CliniciansControllerCreateResponses];

export type CliniciansControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/clinicians/{id}';
};

export type CliniciansControllerRemoveErrors = {
    /**
     * Invalid request
     */
    400: unknown;
    /**
     * Clinician not found
     */
    404: unknown;
};

export type CliniciansControllerRemoveResponses = {
    200: DeleteResultDto;
};

export type CliniciansControllerRemoveResponse = CliniciansControllerRemoveResponses[keyof CliniciansControllerRemoveResponses];

export type CliniciansControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/clinicians/{id}';
};

export type CliniciansControllerFindOneErrors = {
    /**
     * Invalid request
     */
    400: unknown;
    /**
     * Clinician not found
     */
    404: unknown;
};

export type CliniciansControllerFindOneResponses = {
    200: ClinicianInfoDto;
};

export type CliniciansControllerFindOneResponse = CliniciansControllerFindOneResponses[keyof CliniciansControllerFindOneResponses];

export type CliniciansControllerUpdateData = {
    body: UpdateClinicianDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/clinicians/{id}';
};

export type CliniciansControllerUpdateErrors = {
    /**
     * Invalid request
     */
    400: unknown;
    /**
     * Clinician not found
     */
    404: unknown;
};

export type CliniciansControllerUpdateResponses = {
    200: ClinicianInfoDto;
};

export type CliniciansControllerUpdateResponse = CliniciansControllerUpdateResponses[keyof CliniciansControllerUpdateResponses];

export type VisitsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (1-based)
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * Search term
         */
        search?: string;
        /**
         * Sort direction
         */
        sortBy?: 'ASC' | 'DESC';
        /**
         * Field to sort by
         */
        orderBy?: 'visitedAt';
        /**
         * Filter by patient IDs
         */
        patientIds?: Array<string>;
        /**
         * Filter by clinician IDs
         */
        clinicianIds?: Array<string>;
    };
    url: '/visits';
};

export type VisitsControllerFindAllErrors = {
    /**
     * Invalid query parameters
     */
    400: unknown;
};

export type VisitsControllerFindAllResponses = {
    200: PaginatedVisitInfoDto;
};

export type VisitsControllerFindAllResponse = VisitsControllerFindAllResponses[keyof VisitsControllerFindAllResponses];

export type VisitsControllerCreateData = {
    body: CreateVisitRequestDto;
    path?: never;
    query?: never;
    url: '/visits';
};

export type VisitsControllerCreateErrors = {
    /**
     * Invalid request
     */
    400: unknown;
    /**
     * Patient or clinician not found
     */
    404: unknown;
    /**
     * Visit already exists for this patient and clinician at that time
     */
    409: unknown;
};

export type VisitsControllerCreateResponses = {
    201: VisitInfoDto;
};

export type VisitsControllerCreateResponse = VisitsControllerCreateResponses[keyof VisitsControllerCreateResponses];

export type VisitsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/visits/{id}';
};

export type VisitsControllerRemoveErrors = {
    /**
     * Invalid UUID
     */
    400: unknown;
    /**
     * Visit not found
     */
    404: unknown;
};

export type VisitsControllerRemoveResponses = {
    200: DeleteResultDto;
};

export type VisitsControllerRemoveResponse = VisitsControllerRemoveResponses[keyof VisitsControllerRemoveResponses];

export type VisitsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/visits/{id}';
};

export type VisitsControllerFindOneErrors = {
    /**
     * Invalid UUID
     */
    400: unknown;
    /**
     * Visit not found
     */
    404: unknown;
};

export type VisitsControllerFindOneResponses = {
    200: VisitInfoDto;
};

export type VisitsControllerFindOneResponse = VisitsControllerFindOneResponses[keyof VisitsControllerFindOneResponses];

export type VisitsControllerUpdateData = {
    body: UpdateVisitDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/visits/{id}';
};

export type VisitsControllerUpdateErrors = {
    /**
     * Invalid request or UUID
     */
    400: unknown;
    /**
     * Visit not found
     */
    404: unknown;
};

export type VisitsControllerUpdateResponses = {
    200: VisitInfoDto;
};

export type VisitsControllerUpdateResponse = VisitsControllerUpdateResponses[keyof VisitsControllerUpdateResponses];
